# Generated by Django 3.2.6 on 2021-08-30 16:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniqlink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='untitled', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField(default=datetime.datetime(2021, 9, 6, 16, 13, 4, 353469), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniqlinks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created', 'user'],
            },
        ),
    ]
