# Generated by Django 3.2.6 on 2021-09-02 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniqlink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='untitled', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField(default=datetime.datetime(2021, 9, 9, 10, 20, 12, 560418), editable=False)),
                ('num_contributors', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniqlinks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uniqlink_uuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributors', to='referral.uniqlink')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('contributor_email', 'uniqlink_uuid')},
            },
        ),
    ]
