# Generated by Django 3.2.6 on 2021-08-28 16:30

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uniqlink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('86db9358-19fc-42c8-a53c-d8e0503a8d8e'), primary_key=True, serialize=False)),
                ('title', models.CharField(default='untitled', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField(default=datetime.datetime(2021, 9, 4, 16, 30, 4, 204591), editable=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
