# Generated by Django 3.2.6 on 2021-09-01 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_auto_20210901_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqlink',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 12, 31, 45, 569543), editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set(),
        ),
    ]
