# Generated by Django 3.2.6 on 2021-09-01 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_auto_20210901_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqlink',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 12, 34, 58, 541103), editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('contributor_email', 'uniqlink_uuid')},
        ),
    ]
